//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_books
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public int SUB_CATEGORY_ID { get; set; }
        public string SUB_CATEGORY_NAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
